### ISSUE TITLE
TODO: set up conda caching

### ISSUE THREAD

**Issue by thermokarst** [qiime2/action-library-packaging#5]
Right now the longest step in this action involves bootstrapping a miniconda installation. GHA supports caching: https://github.com/actions/toolkit/tree/main/packages/tool-cache. It would be really great if we could cache the miniconda base install. Bonus: if workflows can re-use the cached install across multiple actions, that would be fabu.

**Comment by lizgehret** [comment]
as mentioned in #7, this was solved via other methods, closing as completed.
